### ISSUE TITLE
Disable the confirmation message on exit

### ISSUE THREAD

**Issue by GoogleCodeExporter** [otros-systems/otroslogviewer#247]
```
The message "Do you want to exit OtrosLogViewer and parse logs with 'grep'?" is 
always displayed on exit and is very annoying. There should be an "Do not ask 
me again" option to disable it at will.
```

Original issue reported on code.google.com by `dou...@gmail.com` on 21 Jan 2013 at 2:58

**Comment by Dounyy** [comment]
Since a Settings panel has been implemented, may it be possible to add a such option?
I am getting really tired of that message... Everytime I am like :
"- Do you want to exit OtrosLogViewer and parse logs with 'grep'?"
"- No, I want to exit OLV to shut down my freaking computer".

**Comment by otros-systems** [comment]
I think that it should  be easy change. As a workaround you can set
"generalBehavior.confirmExit" ti false  in configuration:

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<configuration>
*<generalBehavior>*
* <confirmExit>false</confirmExit>*
*</generalBehavior>*



pt., 4.03.2016 o 10:25 użytkownik Dounyy <notifications@github.com> napisał:

**Comment by Dounyy** [comment]
Thank you for this trick. Can you tell me what is the name of the file that I should edit?

**Comment by otros-systems** [comment]
In home directory .otroslogviewer/config.xml

pt., 4.03.2016 o 10:57 użytkownik Dounyy <notifications@github.com> napisał:
