### ISSUE TITLE
Embed log viewer in a Swing or JavaFX component?

### ISSUE THREAD

**Issue by 77capr** [otros-systems/otroslogviewer#336]
Is this possible? I'd like to provide a button in my app that will show the app's log in a Swing or JavaFX component.

Thanks, Al

**Comment by otros-systems** [comment]
Hi Al.
Embedding OtrosLogViewer is no easy. I think that better way is to run otroslogviewer with passing path to you log file when user click button.
If you run command: 
  ./olv.sh /home/user/some.log
OtrosLogViewer will run and open log file or open log file in running OtrosLogViewer

**Comment by 77capr** [comment]
Starting new processes from an app may be tricky WRT to permissions and paths. It would be a lot smoother to be able to just display a component containing the log. Might this be a worthwhile feature for the future at some point?
