### ISSUE TITLE
Windows Batch File: Problems with directory with white spaces

### ISSUE THREAD

**Issue by Ph1l1ppp** [otros-systems/otroslogviewer#337]
When OtrosLogViewer is zipped to a directory with white spaces, starting the log viewer fails.

Line 54 in batch file has to be changed to

start "OtrosLogViewer" /B %LOCAL_JAVA% %LOG_PROPERTIES% %MEMORY%  -DsingleInstance.startPort= -DOLV_HOME="%OLV_HOME%" -DCURRENT_DIR="%CURRENT_DIR%" -jar "%OLV_HOME%"\lib\OtrosStarter.jar %\* 1>%OUT_FILE% 2>%ERR_FILE%

**Comment by sridhareaswaran** [comment]
Cool :) Worked like charm, after implementing the above fix... kindly make the change in main source,

**Comment by svennissel** [comment]
Bug is resolved with 0097b9eeabfeca0f5131aa2f74012787150086f4
