### ISSUE TITLE
ConnectToSocketHubAppenderAction sets fixed sleep time 4000ms

### ISSUE THREAD

**Issue by modk** [otros-systems/otroslogviewer#343]
This is more a feature request than a real issue, but nevertheless:
I am using Otros Log Viewer to connect to a logback or log4j SocketHubAppender. Currently the update interval seems to be fixed to 4000 ms which can only be changed in the source

```
logDataCollector = new  BufferingLogDataCollectorProxy(logViewPanelWrapper.getDataTableModel(), 4000, configuration);
```

I'd like my users to see new log messages more often, say every second, therefore I'd need to change the update interval. Could this property be made a configuration key in order to set it externally?

Thanks :)

**Comment by otros-systems** [comment]
Hi @modk ,
Unfortunately this is hardcoded. But I think this is a good feature request for 1.3.3
