### ISSUE TITLE
MDC Supprot

### ISSUE THREAD

**Issue by afattahi54** [otros-systems/otroslogviewer#351]
I have reviewed some parts of code and found that the MDC is supported. But I can not use it.
I am looking for a way to display each MDC parameters as new column. 
The log4j pattern is

```
 name=%d %-5p %-30.30c{2}-[%X{UserId}|%X{ServiceSequence}]-%m%n%throwable{full}

pattern=TIMESTAMP LEVEL CLASS-[PROP(UserId)|PROP(ServiceSequence)]-MESSAGE
```

And I try to use PROP with no luck all properties are displayed in one column named properties

**Comment by otros-systems** [comment]
This work as design. OtrosLogViewer model is not supporting dynamic table columns.
