### ISSUE TITLE
"Requirements - Java 6". are you sure not Java 8?

### ISSUE THREAD

**Issue by OhadR** [otros-systems/otroslogviewer#361]
in the Requirements section, it is written "Java 6". but when i tried to build the project with Java 7, i got errors that Java 8 is required.

Am I missing something?

**Comment by otrebski** [comment]
Java 6 is required for latest released version. New version will require Java 8. So if you are building from sources you have to have JDK 8.

**Comment by OhadR** [comment]
thanks!

**Comment by OhadR** [comment]
by the way, i recommend to add a section like "how to build", and to add there the gradle task "dist"; it is not straight forward...
thanks!
