### ISSUE TITLE
project documentation / OTROS with REST API

### ISSUE THREAD

**Issue by OhadR** [otros-systems/otroslogviewer#362]
well, this is not an "issue", but i did not find any blog, so i post this question here: 
is there any documentation about this great project? on its architecture? layers?

i'm interested in writing a web-client that will communicate with otros. I've downloaded the sources, and saw several gradle sub-projects. how can i tell which layer communicate with each other and how? only by digging-in the source? 

what is the best place to wrap in REST API in order to achieve this?

thanks for any help
Ohad

**Comment by otrebski** [comment]
I'm a little bit confused. What this REST API should do?
