### ISSUE TITLE
"Permission Denied" when trying to get file/dir with other permissions (how to sudo)

### ISSUE THREAD

**Issue by OhadR** [otros-systems/otroslogviewer#370]
is there a way I can "sudo" from otros?  

i have a user that does not have permissions to get to the log dir. When I connect through SSH, i login and then "sudo su" so I get permissions. is there a way to "sudo" but via otros?

**Comment by otros-systems** [comment]
Hi OhadR. I don't think it is possible. It uses scp protocol to access files.

**Comment by p91paul** [comment]
@OhadR if you have root access, it should be easy to get read permissions for your user/group to those files/dirs!
