### ISSUE TITLE
Is it possible to change the font size or proportion?

### ISSUE THREAD

**Issue by negora** [otros-systems/otroslogviewer#389]
Hello:

I've tried the application in the following systems:

* Kubuntu 14.04 with OpenJDK 8.
* Linux Mint 17.3 Mate with Oracle JDK 8.

But in both them the text looks like very small. I'm NOT using a HiDPI display, by the way. The font size in both systems is set to 13 pixels, but in OtrosLogViewer it looks like as if it were set to 11 or 10 pixels.

Is there a way to set the font size or proportion through the command line or a configuration file? I believe that the application is using the Substance L&F (Look and Feel), but I'm not sure if it's supposed to take the font size from the desktop environment automatically, or if I can set it by hand.

Thank you.

**Comment by otros-systems** [comment]
Hi Negora
This is supported in new version. If you want to have this feature before release, build from sources.
