### ISSUE TITLE
Clear table / "Remove log events" do nothing in the first tab

### ISSUE THREAD

**Issue by lalili** [otros-systems/otroslogviewer#407]
I'm using build 1.4.2
**In the first viewer tab** "Clear table" button does not work
Same about "Remove log events" option in right-click menu

In the next tabs the buttons work as expected

thanks
![javaw_2016-07-06_12-01-29](https://cloud.githubusercontent.com/assets/11541573/16625223/7580bc4c-4371-11e6-89e2-430834f04e5a.png)

**Comment by otros-systems** [comment]
Issue fixed in https://github.com/otros-systems/otroslogviewer/pull/408
