### ISSUE TITLE
Empty tables

### ISSUE THREAD

**Issue by borayeris** [otros-systems/otroslogviewer#411]
I can connect to my server by SSH but after I open apache log table is empty. What am I doing wrong?

**Comment by borayeris** [comment]
?

**Comment by p91paul** [comment]
Have you created a parser configuration for apache? olv is not capable of showing arbitrary logs, it needs a specific configuration for each.

**Comment by borayeris** [comment]
Oh I didn't know that I should. I am using "Tail Autodetect log format". Shouldn't it work?

**Comment by p91paul** [comment]
It autodetects among the formats it knows. Use tools->pattern parser editor to create a parser configuration, when you are satisfied with the result save it, then restart olv and you'll be able to parse your logs. olv is powerful, but requires a bit of time to set it up.
