### ISSUE TITLE
Log file is sometimes shown as "imaginary Folder"

### ISSUE THREAD

**Issue by lalili** [otros-systems/otroslogviewer#416]
I'm using OLV 1.4.4 from Downloads page

Sometimes an open log file starts to show as "imaginary folder". After restart of OLV the problem is fixed

![image](https://cloud.githubusercontent.com/assets/11541573/17943095/032cb002-6a08-11e6-96ba-15afaf7ede42.png)

**Comment by lalili** [comment]
What is the meaning of "type = imaginary"?

**Comment by otrebski** [comment]
This is how how this folder is detected by apache commons VFS. I think that imaginary can be symbolic link.
