### ISSUE TITLE
bad link in wiki ShowCallHierarchy page to example hierarchy.log

### ISSUE THREAD

**Issue by buzz3791** [otros-systems/otroslogviewer#424]
The wiki page

https://github.com/otros-systems/otroslogviewer/wiki/ShowCallHierarchy

has a bad link to the example log.

New link:
https://github.com/otros-systems/otroslogviewer/blob/master/OtrosLogViewer-app/src/test/resources/hierarchy/hierarchy.log

Old link:
http://code.google.com/p/otroslogviewer/source/browse/trunk/test/resources/hierarchy/hierarchy.log

I would happily edit the page but I don't seem to have permissions.

**Comment by otrebski** [comment]
Thanks @buzz3791
