### ISSUE TITLE
Log4j XML event with nested CDATA is silently ignored

### ISSUE THREAD

**Issue by gerwinjansen** [otros-systems/otroslogviewer#426]
I have logfiles created with older versions of Log4j. Those versions have known issues with nested CDATA:
- [9514 Chainsaw cannot load files if messages contain CDATA](https://bz.apache.org/bugzilla/show_bug.cgi?id=9514)
- [37560 Does not handle embedded xml correctly](https://bz.apache.org/bugzilla/show_bug.cgi?id=37560)

See the links for example log events.
Those events are silently ignored. This is very annoying and, even worse, it make the logviewer unreliable.

**Comment by otrebski** [comment]
Thanks Gerwin for fix!
