### ISSUE TITLE
can't open log file from remote host

### ISSUE THREAD

**Issue by RamuJeevitha** [otros-systems/otroslogviewer#428]
There is no option under Open to connect to remote host.
Version : 1.4.5
![image](https://cloud.githubusercontent.com/assets/24934830/21676891/b06aa756-d35d-11e6-9131-f7a3d808b65d.png)

**Comment by otros-systems** [comment]
@RamuJeevitha OtrosLogViewer is using OtrosVfsBrowser, so in path you can type `sftp://host/ <enter>`. For samba (windows share) user `smb://host/resource`
