### ISSUE TITLE
Regression: olv-1.4.5 crashes when opening logfile (worked fine in 1.4.4)

### ISSUE THREAD

**Issue by rggjan** [otros-systems/otroslogviewer#437]
Opening the attached [logfile](https://github.com/otros-systems/otroslogviewer/files/761000/crashing_log.zip) crashes in [olv-1.4.5](https://cloud.githubusercontent.com/assets/128554/22742956/dbb6e336-ee18-11e6-8869-ebf955caf27f.PNG), while it worked fine in [olv-1.4.4](https://cloud.githubusercontent.com/assets/128554/22742999/0526db2c-ee19-11e6-8b64-b741a6800db7.PNG) on Windows 10.

**Comment by otrebski** [comment]
@rggjan Can you send  pattern used to import log?

**Comment by rggjan** [comment]
I think this happens when using the default patterns...

Can't you reproduce it with a standard install?

**Comment by otrebski** [comment]
I'm unable to reproduce if I don't know what log pattern you have used to parse logs

**Comment by rggjan** [comment]
Hi @otrebski , as I already mentioned, this error happens when:

- Downloading olv-1.4.5 from the website
- Opening it via olv.bat
- Drag-and-dropping mentioned logfile into the GUI

I also don't know what log pattern olv uses in this case, how can I find out when it crashes?
- Jan

**Comment by rggjan** [comment]
How can I open this bug again? Or should I open another bug report?

**Comment by rggjan** [comment]
Oh, actually it seems to be fixed in olv-1.4.6, as I just noticed. Cool. No need to open up the bug again, then.

**Comment by otrebski** [comment]
Thanks @rggjan
