### ISSUE TITLE
No signature of method on ScalaFormater:test

### ISSUE THREAD

**Issue by archenroot** [otros-systems/otroslogviewer#438]
I cloned and tried to build this cool tool and experienced:
:ScalaFormatter:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ScalaFormatter:test'.
> No signature of method: org.gradle.StartParameter.isColorOutput() is applicable for argument types: () values: []

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by otrebski** [comment]
I have noticed the same. Try to use gradle wrapper:
```
./gradlew clean test dist
```

**Comment by otrebski** [comment]
I have updated scalatest plugin and gradle wrapper. Please use Gradle 3.4.1 or gradle wrapper
