### ISSUE TITLE
Cant implement new plugins

### ISSUE THREAD

**Issue by gulcebasar** [otros-systems/otroslogviewer#445]
Hi,

I tried implementing a new log filter as stated in the wiki. I implement the log filter from import pl.otros.logview.api.pluginable.LogFilter. Otros does load the class, but I cant seem to get it to add the new filter to the existing filters menu. How do I do that?

**Comment by otrebski** [comment]
Hi @gulcebasar 
Is your project public? I can take a look

**Comment by gulcebasar** [comment]
Hi @otrebski I will upload it now. It is most likely because I lack the knowledge to develop the plugin but still I couldn't manage to get it to work.

**Comment by gulcebasar** [comment]
I solved the issue by, instead of implementing pluginable.LogFilter I extended the AbstractLogFilter
