### ISSUE TITLE
Drag and Drop not working on Mac OS X 10.12.6

### ISSUE THREAD

**Issue by rggjan** [otros-systems/otroslogviewer#446]
1) Drag and drop a file from file explorer (Finder) to the main screen of otros

- Expected: Log file is opened, same as on windows
- Result: An error is displayed ("null")

See screenshot. On windows this works fine. Opening it via "tail logfile" also works fine on Mac.

<img width="1344" alt="true" src="https://user-images.githubusercontent.com/128554/29451302-74662afe-8402-11e7-8cce-c29c50f0ac16.png">

**Comment by otrebski** [comment]
@rggjan I can't reproduce it. Can you send application log `$HOME/olv.log`

**Comment by rggjan** [comment]
Is attached...
[olv.log](https://github.com/otros-systems/otroslogviewer/files/1387228/olv.log)

**Comment by otrebski** [comment]
Closed with issue #452
