### ISSUE TITLE
Could not acces to SFTP option on ostrologivewer 1.4.6

### ISSUE THREAD

**Issue by pcouas** [otros-systems/otroslogviewer#447]
Hi,

I have downloaded ostrologviewer 1.4.6 from sourceforge, but i could not find option for acces to SFTP parameter in File Menu . Why ?

https://www.developpez.net/forums/d1753435/logiciels/logiciels-libres-open-source/ostrologviewer-ssh-acces-files/

**Comment by snoerenberg** [comment]
Use sftp://username@host and press enter

**Comment by pcouas** [comment]
thanks
