### ISSUE TITLE
macOS & otros 1.4.6 Nullpointer when browsing for files...

### ISSUE THREAD

**Issue by sgrimm0** [otros-systems/otroslogviewer#448]
Using macOs and otros 1.4.6 always runs into a Nullpointer Exception when browsing for files i.e. "Add more files" then click on any folder an I get:

<img width="1152" alt="bildschirmfoto 2017-10-09 um 15 08 03" src="https://user-images.githubusercontent.com/30872425/31339677-eeafe802-ad03-11e7-8902-e7ffab350416.png">

method and line: FileNameWitTypeTableCellRenderer.getTableCellRendererComponent(FileNameWitTypeTableCellRenderer:52)

current workaround is opening olv in terminal passing the file i want to open...

Also I can not copy full stacktrace out of the error message as there is no copy paste functionality :-(

**Comment by otrebski** [comment]
Thianks, I will take a look

**Comment by otrebski** [comment]
@sgrimm0 
Can you check this version: https://www.dropbox.com/s/44lj7jx299wejmd/olv-1.4.7-SNAPSHOT.zip?dl=0

**Comment by sgrimm0** [comment]
Hey @otrebski ,
good news: The NullPointer seems to be gone with the fixed version from dropbox. I was now able to add a file to the list. Nice :-)

How ever there seem to be additional problems:

After adding the file it appears in a list. When I click on the cell either in the "Log Importer" or  "Can Parse"  or "Content" column (e.g. using the olv.log file itself) getting a NullPointer Exception. Seems to be a bit randomish depending what you click first.
Attached are screens and logs.

How ever these seem to be minor issues the log-file can be imported which is the main thing. Still there seems to be lacking some robustness in the application.

Cheers
<img width="889" alt="bildschirmfoto 2017-10-16 um 10 45 53" src="https://user-images.githubusercontent.com/30872425/31603580-e6424ca2-b260-11e7-81b7-7f7c98516d96.png">
<img width="876" alt="bildschirmfoto 2017-10-16 um 10 46 33" src="https://user-images.githubusercontent.com/30872425/31603582-e8b06cee-b260-11e7-8f51-b6daea849066.png">
[olv_147_20171016.log](https://github.com/otros-systems/otroslogviewer/files/1386774/olv_147_20171016.log)

**Comment by otrebski** [comment]
@sgrimm0  Can you try this fix? https://www.dropbox.com/s/bg1umezeqcs88s9/olv-1.4.7-SNAPSHOT.zip?dl=0

**Comment by edgardleal** [comment]
Hello otrebski, I am using this version ( 1.4.7-SNAPSHOT ) , and until the old version ( 1.4.6 ) i am receiving a NEP when marking a row from context menu:

Notes:
* I am using a custom formattimporter 
* Are you using error report ? Do you peffer error report or github issue ? 
* Should i create a different issue here for this problem ? 

![screen shot 2018-02-02 at 09 46 27](https://user-images.githubusercontent.com/1612250/35733932-080551c0-07fe-11e8-83b5-0369d544097e.png)

**Comment by otrebski** [comment]
I thinks that this is different issue and we should create another one. @edgardleal please create another github issue (Currently I have some issues with error reports).
Is it possible to record screencast?
