### ISSUE TITLE
Log4jPatternLayout doesn't work with default date format ISO8601

### ISSUE THREAD

**Issue by Wood-Xia** [otros-systems/otroslogviewer#449]
I use below pattern 
`<PatternLayout pattern="%d{ISO8601} %-5p [%t] %m%n"/>`
in log4j2.xml config file.
The log looks like
`2017-10-14T23:02:45,412 INFO  [main] waiting to stop...`

But the log format can't be detected by any pre-defined parser in the olv-1.4.6 binary package.
I assume it should be detected by predefined parser in log4j-1-native.pattern file.

**Comment by otrebski** [comment]
In 1.4.8 It will be possible to convert Log4j/logback pattern to OtrosLogViewer definition. It is already merged into master.
By the way, you can add `log4j-1-native.pattern` file with following content:
```properties
dateFormat=yyyy-MM-dd HH:mm:ss,SSS
name=%d{ISO8601} %-5p [%t] %m%n 
type=log4j, pattern=TIMESTAMP LEVEL [THREAD] MESSAGE
charset=UTF-8
```
