### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by KiranMohan** [otros-systems/otroslogviewer#451]
First using this application. Very useful.

But I am noticing continuous HIGH CPU usage (70 - 95%)  while import log files of size 30mb. Dont know about other file sizes.

**Comment by edgardleal** [comment]
Otroslogviewer will load the entire file in memory and run filters, formatters and others.
It depends on your cpu/memory. I normally use files with 8MB what is enough to one day of logs in debug mode ( localhost ). But you need to know how many logs you need analyse, and use the minimum size possible.

**Comment by otrebski** [comment]
@KiranMohan Can you provide more details:
1. Are you importing logs from local file system or network?
2. What is log format?
3. Is it possible to attach log file ?

**Comment by otrebski** [comment]
I have found suspicious  fragment and fixed in 1.4.8 candidate.
