### ISSUE TITLE
Log4J-2.x log importer for socket reader

### ISSUE THREAD

**Issue by donatelloOo** [otros-systems/otroslogviewer#453]
log4j-1.x has reached end of life, so it's time to support log4j-2.x !
The log4j-server "TcpSocketServer" now manage serialized org.apache.logging.log4j.core.LogEvent (instead of the old org.apache.log4j.spi.LoggingEvent).
So it should be good to be able to use a new Log4j2SerilizedLogImporter with the SocketLogReader.
As far as we are concerned it is definitely the main way we use OLV, so the migration to Log4J-2.x depends on this !

**Comment by otrebski** [comment]
According to documentation, using java serialisation is deprecated: https://logging.apache.org/log4j/2.x/manual/layouts.html#SerializedLayout
In log4j2 you can use any appender when sending events to socket:
```xml

<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="warn" name="MyApp" packages="">
    <Appenders>
        <Socket name="socket" host="localhost" port="9500">
            <PatternLayout>
                <Pattern>%d %p %c [%t] %m%n</Pattern>
            </PatternLayout>
        </Socket>
    </Appenders>
    <Loggers>
        <Root level="debug">
            <AppenderRef ref="socket"/>
        </Root>
    </Loggers>
</Configuration>
```

Using OLV you can listen on socket and parse text format.
How to define log pattern in OLV: https://github.com/otros-systems/otroslogviewer/wiki/Log4jPatternLayout

**Comment by donatelloOo** [comment]
Partially yes, it seems a good workaround to send data trough log4J2 socket.
However, I don't really want to depends on a pattern layout, as I want to collect all generated data, and use or filter it later, depending on analysis needs.

Why not supporting the JsonLayout alternative which provides exactly the same data, but does not rely on Java Serialization ?

**Comment by otrebski** [comment]
Generic JSON layout is supported. You can specify mapping from JSON objects to log event in OLV
Go to menu `Tools` -> `Show JSON pattern parser editor`

You can parse Log4j2 JSON format with following definition:

```properties
type=json
name=Log4j2 JSON
description=Parser for defualt log4j2 JSON format

level=level
message=message
date=timeMillis
dateFormat=timestamp
thread=thread
file=location.file
class=source.class
method=source.method
line=source.line
logger=loggerFqcn
mdcKeys=contextMap.bar, contextMap.foo, 
```

Drawback of this solution is that you have to list all MDC keys used in you application.

Documentation: [https://github.com/otros-systems/otroslogviewer/wiki/Parsing-logs-in-JSON-format](https://github.com/otros-systems/otroslogviewer/wiki/Parsing-logs-in-JSON-format)

@donatelloOo Let me know if this solves your problem.

**Comment by donatelloOo** [comment]
Sounds good !
Let me a few days to give it a try.

**Comment by donatelloOo** [comment]
Sounds good !
Let me a few days to give it a try.

**Comment by donatelloOo** [comment]
Hi again,

I found several drawbacks when using JsonLayout solution:

1. Using a JSON log file with a JSON parser in OLV:

 *Using Log4j2 file appender configuration:*
 **Note:** use property `stacktraceAsString=true` :

 ```xml
 <?xml version="1.0" encoding="UTF-8"?>
 <Configuration status="WARN" xmlns="http://logging.apache.org/log4j/2.0/config">
     <Appenders>
         <File name="file" fileName="target/logs/app.log">
             <JsonLayout complete="false" properties="true" locationInfo="true" includeStacktrace="true"
                 stacktraceAsString="true" />
         </File>
     </Appenders>
     <Loggers>
         <Root level="DEBUG">
             <AppenderRef ref="file" />
         </Root>
     </Loggers>
 </Configuration>
 ```

 *Using OLV JSON parser configuration:*
 **Note:** map stacktrace as note `note=thrown.extendedStackTrace` :

```properties
type=json
name=Log4j2 JSON
description=Parser for default log4j2 JSON format

level=level
message=message
date=timeMillis
dateFormat=timestamp
thread=thread
file=source.file
class=source.class
method=source.method
line=source.line
logger=loggerName
mdcKeys=threadId,threadPriority,contextMap.mdc-key

ndc=contextMap.ndc-key
note=thrown.extendedStackTrace
```

- **works not so bad**: stacktrace is displayed in message details (in note), but this note field cannot be used anymore.
- this is **not a socket server solution** where several applications can send their logs to the same server, and OLV is just a client viewer

2. Using a socket listener on OLV with a JSON parser:

*Using Log4j2 socket appender configuration for Log4j2:*
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="WARN" xmlns="http://logging.apache.org/log4j/2.0/config">
    <Appenders>
        <Socket name="socket" host="localhost" port="4560">
            <JsonLayout complete="false" properties="true" locationInfo="true" includeStacktrace="true" />
        </Socket>
    </Appenders>
    <Loggers>
        <Root level="DEBUG">
            <AppenderRef ref="file" />
        </Root>
    </Loggers>
</Configuration>
```

- **does not seems to work** (nothing appears, no error message in internal logs ... whereas the JSON importer is working good)
- this is **not a socket server solution** where several applications can send their logs to the same server, and OLV is just a client viewer

NB: I used `org.apache.logging.log4j:log4j-core:2.10.0`

A good fix should be to support a "Connect to Log4J2 socket server" which ask for a parser (we choose our JSON parser), and a special management for the trowables case.
What can you do ?

**Comment by otrebski** [comment]
I think that specific Log parser have to be create. I have created issue #485

**Comment by otrebski** [comment]
@donatelloOo I have implemented Log4j2 JSON log parser
