### ISSUE TITLE
Can't parse dot in log4 pattern 

### ISSUE THREAD

**Issue by thangdc94** [otros-systems/otroslogviewer#494]
Here is my log4j pattern config. 
```
type=log4j-native
conversionPattern=%d{ISO8601} %-5p [%t] %C{2}.%M(%F:%L) - %m%n
name="Mylog4j %d{ISO8601} %-5p [%t] %C{2}.%M(%F:%L) - %m%n"
charset=UTF-8
```
It works if I replace **dot(.)** by **dash(-)**. 
I tried to add a back slash before dot but it doesn't work. 
How can I make it works with dot?

**Comment by otrebski** [comment]
I'm afraid that this is a limitation of log parser. It is not so cleaver to break into parts `p.a.c.k.a.g.e.class.method`.
