### ISSUE TITLE
Send anonymous stats to server

### ISSUE THREAD

**Issue by otrebski** [otros-systems/otroslogviewer#499]

**Comment by canadug** [comment]
@otrebski - Please provide an overview of the anonymous stats that are being sent to the mothership?  Also, would it be possible to have an opt-out feature for this for folks that have privacy concerns?

Thanks.

**Comment by otrebski** [comment]
During first use wizard you are asked if you want to send stats. But you are right that it is missing option in preferences to turn it off. I have create 2 issues:

https://github.com/otros-systems/otroslogviewer/issues/509
https://github.com/otros-systems/otroslogviewer/issues/510
