### ISSUE TITLE
Dual screen Monitor support with different resolutions

### ISSUE THREAD

**Issue by svennissel** [otros-systems/otroslogviewer#508]
If the main Monitor has a smaller resolution then the second monitor the Window will positioned out of the monitor. I have also problem to maximize the window on the bigger second monitor.

I found on Problem in the class LogViewMainFrame#initPosition()
`Toolkit.getDefaultToolkit().getScreenSize()` is wrong it store the sum of all Monitor sizes. See https://stackoverflow.com/questions/6322627/java-toolkit-getting-second-screen-size
In this case is better to use
```
this.getGraphicsConfiguration().getDevice().getDisplayMode().getHeight()
this.getGraphicsConfiguration().getDevice().getDisplayMode().getWidth()
```

Also `GuiUtils#centerOnScreen()`
better
```
target.getGraphicsConfiguration().getDevice().getDisplayMode().getWidth()
target.getGraphicsConfiguration().getDevice().getDisplayMode().getHeight()
```

Also `SuggestionDocumentListener#setSuggestionWindowLocation()`
better
`suggestionWindow.getGraphicsConfiguration().getDevice().getDisplayMode().getHeight()`

**Comment by otros-systems** [comment]
@svennissel Can you prepare merge request ?

**Comment by svennissel** [comment]
My first pull request: https://github.com/otros-systems/otroslogviewer/pull/524
The position of the JFrame is now correct. But on the bigger second monitor the window maximize only to the size of the primary monitor.

**Comment by svennissel** [comment]
I found the Problem of "Fullscreen on bigger secondary screen".
This is a example Application can reproduce the bug:
`public class TestFrame extends JFrame {
  public TestFrame() {
    super();
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    getContentPane().add(new Label("Bug"));
    pack();
    setVisible(true);
  }

  public static void main(String[] args) throws Exception {
    SwingUtilities.invokeAndWait(() -> {
      try {
        UIManager.setLookAndFeel("org.pushingpixels.substance.api.skin.SubstanceBusinessLookAndFeel");
      } catch (Exception e) {
        e.printStackTrace();
      }
      new TestFrame();
    });
  }
}`

If you maximize the window, it will be not bigger than the primary screen.

If you commend out "UIManager.setLookAndFeel("org.pushingpixels.substance.api.skin.SubstanceBusinessLookAndFeel");" than the window resize correctly.

Also if you commend out in class LogViewMainFrame the line: LookAndFeelUtil.initLf(c.getString(ConfKeys.APPEARANCE_LOOK_AND_FEEL, SubstanceBusinessBlackSteelLookAndFeel.class.getName()));

**Comment by otros-systems** [comment]
Thanks @svennissel
