### ISSUE TITLE
Can't seem to open logs with anything other than the basic "autodetect" filter

### ISSUE THREAD

**Issue by PMLavigne** [otros-systems/otroslogviewer#539]
Apologies if I'm just doing something wrong, but when I used OLV in the past I remember there being several additional menu entries that allow you to specify a particular parser to use to parse your log. As far as I can tell those have disappeared (tried 1.4.9 and 1.4.11). Without these buttons I can't figure out how to get the program to parse my log in anything other than the "autodetected" generic formatter, which doesn't really work (it gets the time and severity but everything else is just lumped into "message").

Here's a screenshot of where the buttons used to be, note how there still appears to be a _section_ for the buttons (the two horizontal lines below "Save Log Investigation") but the section is empty:

![screen shot 2018-08-16 at 10 48 41 am](https://user-images.githubusercontent.com/6911961/44216049-021a6d80-a142-11e8-84f0-79683d4b983e.png)

The same sort of empty space appears on the home screen as well:

![screen shot 2018-08-16 at 10 49 24 am](https://user-images.githubusercontent.com/6911961/44216099-178f9780-a142-11e8-87bd-bb170ca458de.png)

Again, sorry if I'm just doing something wrong, I haven't used OLV in years, but if there's some way to select the parser to use like there used to be I can't seem to find it.

Additional info:
OLV Version: 1.4.9 - 1.4.11
OS Version: MacOS 10.13.6
Java version: 
```
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
```

Log: [olv-issue.log](https://github.com/otros-systems/otroslogviewer/files/2294142/olv-issue.log)

Let me know if you need me to try anything else or get any other info, and sorry if I'm just being dumb!

**EDIT**: Something I forgot to mention, I tried changing the look and feel to the different options (dark theme, default "MacOS" theme, etc) since I know sometimes Java's UI stuff can be a bit finicky, but it didn't make a difference.

**Comment by JesseMaiden** [comment]
To confirm,

Have you tried creating a pattern using the Log4j Pattern Parse Editor located under Tools?
![image](https://user-images.githubusercontent.com/42048537/44634748-c8c8d580-a96b-11e8-8741-22b9bb4c5fab.png)

https://github.com/otros-systems/otroslogviewer/wiki/Log4jPatternLayout

**Comment by maddingo** [comment]
I have the same issue. I can open the pattern parse editor and create a new pattern. But then there is no way of actually using the parser. As PMLavigne says, there is no way of opening a log file with a different parser. I could find the issue myself and try to submit a PR but haven't managed to build the project.

**Comment by PMLavigne** [comment]
I've definitely created a pattern with the parser (both on first run when it opens it automatically, and then again later manually) but I'll try one more time just to be sure. As far as I can tell, the pattern editor works fine and the pattern saves, but then I can't use it in any way - the default (and only available) way to open a log just "autodetects" to the default one, and I can't select any other parser.

**Comment by tamboril** [comment]
I just figured this out.  There is an empty UUID-named pattern file created for you in ~/otroslogviewer/plugins/logimporters.  Save your custom pattern into that file.  It appears to be the only one honored.

**Comment by dwburrill** [comment]
Protip - If you choose "File > Merge Log Files", then "Add more files" you can then still pick a single log file and change the log importer from the drop down in that column.  I'm not sure why they removed that functionality from the "File > Open Log Files" UI screen.  It used to be there I believe.

**Comment by maddingo** [comment]
Have a look at #566

**Comment by svennissel** [comment]
I hope the Solution of #593 is useful. Is added in upcoming version 1.4.16

**Comment by veda-tschoening** [comment]
So what's the status of this, how am I reliably able to choose a log parser when opening a file? There's one PR mentioned still open and not merged. One PR is linked, was merged, but reverted again. So we are back to not having any chance to choose one concrete parser for some log file?
