### ISSUE TITLE
running olv.bat get Error: Unable to access OtrosStarter.jar

### ISSUE THREAD

**Issue by GGK01GGK** [otros-systems/otroslogviewer#549]
Hi, 

I'm new on olv I want to try it. 
**Steps I did:**
- downloading and unzip Version 1.4.12
- running olv.sh in directory OtrosAppDist\src\dist\scriptsWin\olv.sh
- get the error: Unable to access jarfile -> OtrosAppDist\src\dist\scriptsWin\lib\OtrosStarter.jar

the mentioned file does not exist in the filesystem either

Thanks for supporting me

GGK

**Comment by shahamit** [comment]
Yes, I got the same error on starting the log viewer. Seems we are missing something basic. Nothing is mentioned in the [wiki ](https://github.com/otros-systems/otroslogviewer/wiki/RequirementsAndInstallation)too. Kindly guide us.

**Comment by tangguochang** [comment]
I have the same problem too
I think we should run gradlew build first ， but after build ， the app still can not startup

**Comment by Kenzi007220** [comment]
Same problem, any advice?

**Comment by svennissel** [comment]
You donwload the source code. You must download [olv-1.4.15.zip](https://github.com/otros-systems/otroslogviewer/releases/download/v1.4.15/olv-1.4.15.zip) for example.
