### ISSUE TITLE
Unexpected end of ZLIB input

### ISSUE THREAD

**Issue by nuessgens** [otros-systems/otroslogviewer#550]
When I try to open a .gz file via sftp i get the following error: 
`ERROR 12 Okt 2018;09:38:02.472 [AWT-EventQueue-0] pl.otros.logview.gui.actions.TailLogActionListener Cannot open tailing input stream for sftp://<host>/var/log/ucrs/app.log.2.gz, Unexpected end of ZLIB input stream`

I tried with 1.4.11 and 1.4.12.

**Comment by svennissel** [comment]
fixed in upcoming version 1.4.16
