### ISSUE TITLE
broken google code links in wiki

### ISSUE THREAD

**Issue by lluccia** [otros-systems/otroslogviewer#551]
There is a lot of broken links in the wiki to the old google code site. 
examples in page: https://github.com/otros-systems/otroslogviewer/wiki/BatchProcessing

Apparently there is no way to do a pull request to the wiki pages, so I forked the project wiki https://github.com/lluccia/otroslogviewer.wiki.git and did a lot of link updates. [patch attached](https://github.com/otros-systems/otroslogviewer/files/2646599/0001-fix-broken-outdated-links-in-wiki-pages.patch.zip)

I also noticed that in the repository there is a "wiki" branch that I also updated in my fork, but then I noticed that it did not reflect the pages currently published to the wiki.

Can you please review and update the wiki?

**Comment by svennissel** [comment]
I hope i have fixed most of the links. And update a lot of screenshots.
