### ISSUE TITLE
Stuck "Loading..." files in directory

### ISSUE THREAD

**Issue by cdalexndr** [otros-systems/otroslogviewer#559]
OS Windows 10.
When trying to open a log file, I select a directory from favorites, and then it hangs in a progress bar "Loading...". Clicking "Skip checking links" does nothing.
The directory is from local drive and it contains 3000 files, and a log file that is actively written to.
The browsing should be fast when listing the contents of the directory, as the windows explorer works instantly showing all files. If any work is done on the files, it should be done when selecting it (preview) or when opening it.

**Comment by cdalexndr** [comment]
After I deleted the majority of obsolete files form the directory, now with only 4 files remaining, the loading process completes, and it displays the old 3000 files list. After a refresh it displays the correct 4 remaining files.

**Comment by TonyMercer** [comment]
I have a similar issue. Windows 10 browsing a folder of 116 zipped log files + 1 active unzipped log file on a windows 10 network share. Stuck on 'loading...' for over 15mins before I killed it.
Copying the 4 log files off to another folder and browsing that from LogView works fine.
Happy to help with any test cases & logs needed to help

**Comment by svennissel** [comment]
Can reproduce it better if i set in BaseNavigateAction SWITCH_TO_LOADING_TIME to 1.
If i open a dirctory witch need a little bit more loading time and than go back I got the same Problem:
21:22:58.680 [AWT-EventQueue-0] DEBUG p.o.v.b.actions.BaseNavigateAction - Executing
21:22:58.680 [pool-1-thread-1] INFO  pl.otros.vfs.browser.VfsBrowser - Executing going up
21:22:58.680 [pool-1-thread-1] INFO  pl.otros.vfs.browser.VfsBrowser - goToFileObject by fileobject
21:22:58.680 [pool-1-thread-1] DEBUG pl.otros.vfs.browser.util.VFSUtils - fileType is folder
21:22:58.681 [pool-1-thread-1] INFO  pl.otros.vfs.browser.VfsBrowser - Have 64 files in file:///C:/Users/sven
21:22:58.681 [pool-1-thread-1] DEBUG pl.otros.vfs.browser.util.VFSUtils - Checking for SFTP links
21:22:58.681 [pool-1-thread-1] INFO  pl.otros.vfs.browser.util.VFSUtils - Checking SFTP links took 0 ms [0.0ms/file]
21:22:58.684 [AWT-EventQueue-0] DEBUG pl.otros.vfs.browser.VfsBrowser - Updating selection
21:22:58.684 [AWT-EventQueue-0] DEBUG pl.otros.vfs.browser.VfsBrowser - Updating selection
21:22:58.684 [AWT-EventQueue-0] DEBUG pl.otros.vfs.browser.VfsBrowser - Updating selection
21:22:58.688 [AWT-EventQueue-0] DEBUG pl.otros.vfs.browser.VfsBrowser - Updating selection
21:22:58.691 [AWT-EventQueue-0] DEBUG pl.otros.vfs.browser.VfsBrowser - Updating selection
21:22:58.724 [AWT-EventQueue-0] DEBUG p.o.v.b.actions.BaseNavigateAction - Updating UI after base action
21:22:58.724 [AWT-EventQueue-0] DEBUG pl.otros.vfs.browser.VfsBrowser - Showing result table
21:22:58.724 [AWT-EventQueue-0] DEBUG pl.otros.vfs.browser.VfsBrowser - Showing loading panel

**Comment by svennissel** [comment]
fixed in 1.4.16
