### ISSUE TITLE
How to display a simple text log ?

### ISSUE THREAD

**Issue by cuistax** [otros-systems/otroslogviewer#573]
Hello,

My question may sound stupid, but I just want to open a log file containing raw text (no formatting whatsoever).

I can open the log file, but the app does not show me anything.

I just want to see the raw lines, you know. What should I do ?

Thanks !

**Comment by svennissel** [comment]
Create a parser "tools->Show Log4j pattern parser editor"

type=log4j
pattern=MESSAGE
dateFormat=yyyy-MM-dd HH:mm:ss,SSS
name=Textfile Parser
charset=utf8

And save it
This is not relay the use case of otros
