### ISSUE TITLE
Directory structure 

### ISSUE THREAD

**Issue by hellboy81** [otros-systems/otroslogviewer#576]
Due on some restrictions I cannot download compiled binary.

I have compiled project on Heroku but I still cannot start app due on wrong jar files locations.

Please provide the right directory structure to run Otros properly

**Comment by svennissel** [comment]
I can start the application by starting LogViewMainFrame main Method alternative you can run "gradle dist" and under OtrosAppDist/build/distributions/ you habe the zip file with the application
