### ISSUE TITLE
Update support of more secure SSH algorithm

### ISSUE THREAD

**Issue by CentroricercheRPS** [otros-systems/otroslogviewer#582]
When I connect with SFTP with hosts that have disabled support to obsolete and vulnerable SSH algorithm and cyphers I get this error:

![image](https://user-images.githubusercontent.com/31473785/115210032-78937880-a0fe-11eb-80b7-f541c9482e44.png)

**Comment by svennissel** [comment]
The new library did not support all of the newest algorithms, but i hope the most of them. Please test it with the upcoming version 1.4.16
