### ISSUE TITLE
Hide SFTP password from URI in Open log file dialogue

### ISSUE THREAD

**Issue by satopuermayr** [otros-systems/otroslogviewer#592]
When opening logfiles in otros log viewer with an sftp url (for example: sftp://<user>:<password>@<host>....)

would it be possible to add an option to hide the password part so it is not easily leaked when using otros in a situation where the screen might be shared?

Thank you for considering!

**Comment by svennissel** [comment]
It you type sftp://domain.org you get the password Dialog. This Dialog ca save username and password. Why did you type the username and password directly to url?

**Comment by satopuermayr** [comment]
I did not even know this was an option! Thank you!
