### ISSUE TITLE
Can't check latest version

### ISSUE THREAD

**Issue by DavidAccola** [otros-systems/otroslogviewer#602]
I'm wondering if this happens to others as well:

Replication steps:

-Download https://github.com/otros-systems/otroslogviewer/releases/download/v1.4.16/olv-1.4.16.zip
-Unzip to C:\Tools
-Run olv.bat and complete the wizard with all settings as default

-On startup: "Can't check latest version" shows in the lower left.
-Help > Check for new version: "Problem with checking new version: Unable to check latest version"

I've tried this on 2 different machines with the same result. One runs Windows 10, the other Windows 11.

**Comment by svennissel** [comment]
Yes that is a known Bug. I think it is time to disable this Feature or reimplement it Form GitHub hosting.

**Comment by svennissel** [comment]
I have create a fix for next version in pull request #606.
@DavidAccola : Can you test it on Windows?
Latest Version: https://drive.google.com/file/d/1ZsXh0tJj1UYr7ALCwNkl8Fz5h51bEyFh/view?usp=sharing
Fake Old Version 1.0.0: https://drive.google.com/file/d/1KrpkQgLAWdClAjNkFZy8ean3bAVZqY2U/view?usp=sharing
