### ISSUE TITLE
Sort by message

### ISSUE THREAD

**Issue by DavidAccola** [otros-systems/otroslogviewer#603]
Current state: When viewing a parsed log file, it is possible to order by ID and Time only.

Request: It would be very useful to be able to order by Message.
(It would also be useful to be able to order by File and Thread.)

**Comment by svennissel** [comment]
I have create a fix. Can you test it? 
[https://drive.google.com/file/d/1ZsXh0tJj1UYr7ALCwNkl8Fz5h51bEyFh/view?usp=sharing](https://drive.google.com/file/d/1ZsXh0tJj1UYr7ALCwNkl8Fz5h51bEyFh/view?usp=sharing)

**Comment by DavidAccola** [comment]
This is awesome! The only thing I noticed is that LINE is currently doing a lexicographic sort where it should probably be doing a numerical sort.

Example of current behavior:
1
118
2
3

**Comment by svennissel** [comment]
The line column is a Text (String) column. I don't think it is a good idea to change it to number. It also can contains letters!?

Created a pull request #605 for it. It will be added to next version. Thank you for testing.
