### ISSUE TITLE
Unable to parse zip

### ISSUE THREAD

**Issue by DavidAccola** [otros-systems/otroslogviewer#608]
OtrosLogViewer can parse a .log without issue, but when I zip the same file, it cannot parse the .zip.

Attaching example files.
[testing.log](https://github.com/otros-systems/otroslogviewer/files/8516487/testing.log)
[testing.zip](https://github.com/otros-systems/otroslogviewer/files/8516488/testing.zip)

Rep steps:
Select testing.log > "Can parse testing.log"
Select testing.zip > "Can't parse testing.zip"

**Comment by nuessgens** [comment]
I'm not sure if OTROS has zip file support.
All I know is that `.gz` is explicitly implemented.

The complete FS handling relies on apache commons vfs.

So one is able to open a zip file by specifing a `zip` uri.

I was able to open your `testing.zip` by using the URI `zip:file:///tmp/testing.zip!/testing.log`

What would be the desired behavior?
Without looking into detail (/knowing the effort) would it be sufficient for the file-chooser dialog to "treat" zip-files as folders (like windows-explorer does) 

Or should we open the zip-file as log in case it just contains one log?

**Comment by DavidAccola** [comment]
@nuessgens This is what I found in the documentation as far as expected behavior: https://github.com/otros-systems/otroslogviewer/wiki/OpeningLogs#open-compressed-archives

_"If one log file is compressed in a zip... archive you can open the file with the 'open' button or per double click."_

_"If you have compressed more than one log files or mixed with other files you can explore the archive by putting the type at the beginning of the location text field. Ex: .zip:file:///C:/moreThanONeLogFile.zip!/"_

So from that I'd say on double click/open, open the zip as log.

**Comment by svennissel** [comment]
This is a documentation issue (Joke for me and @nuessgens :-) ).

@nuessgens is right, but i fixed this and implement opening zipped logfiles. 
Please Try this:
[https://drive.google.com/file/d/1qJDZeJgwyziOQOn6ZK-qiUQls4_oi-Qr/view?usp=sharing](https://drive.google.com/file/d/1qJDZeJgwyziOQOn6ZK-qiUQls4_oi-Qr/view?usp=sharing)

**Comment by DavidAccola** [comment]
Tested olv-1.4.17-RC1 and it looks great! Thanks @svennissel.
