### ISSUE TITLE
Respect numbers in file-names for sorting in "Open file" dialog

### ISSUE THREAD

**Issue by nuessgens** [otros-systems/otroslogviewer#618]
Enhancement request for a windows-like sorting of files in the "open file" dialog containing number suffixes.

Assume the following files created by e.g. logrotate
* `test.log`
* `test.log.1.gz`
* `test.log.100.gz`
* `test.log.2.gz`

It would be great to have the opportunity (or implemented in general?) that the sorting respects such numeric fractions in file-names that the resulting view would contain a sorted list like follows:
* `test.log`
* `test.log.1.gz`
* `test.log.2.gz`
* ....
* `test.log.100.gz`

**Comment by svennissel** [comment]
It will be implemented as general behaviour.
