### ISSUE TITLE
Date parsing issue

### ISSUE THREAD

**Issue by DavidAccola** [otros-systems/otroslogviewer#634]
Date 5/1 is parsing as 11/1 for some reason. Could be user error, but if it is I'm missing what it could be.

**Example log contents**
"Sun, 01 **May** 2022 16:11:05 GMT" POST foo bar

**Parsed timestamp displays as:**
2022-**11**-01 16:00:05.000

**OtrosLogViewer pattern used**
type=log4j
rePattern="[\\S]{3}, ([0-9]{2} [\\S]{3} [0-9]{4} [0-9]{2}:[0-9]{2}:[0-9]{2}) GMT" (GET|PUT|DELETE|POST|HEAD|CONNECT|OPTIONS|TRACE) (\\S*)(.*)
dateFormat=dd MMM yyyy HH:MM:ss
name=example
charset=windows-1252

TIMESTAMP.group=1
METHOD.group=2
NDC.group=3
MESSAGE.group=4

**Comment by benlazaro** [comment]
I think the problem has to do with the minutes in the format. Can you
change HH:MM:ss in the dateFormat Field to have lowercase ‘mm’ instead?
It must be that capital ‘M’ stands for the month and lowercase ‘m’ is for minutes.

**Comment by DavidAccola** [comment]
Ah, that makes sense. That was 100% it, thanks! This can be closed. 🙂
