### ISSUE TITLE
Viewing log fails with long first entry

### ISSUE THREAD

**Issue by jthalmai** [otros-systems/otroslogviewer#636]
One of our logs that had a very long stacktrace as the first entry of the log file failed to open correctly. I added a reduced version of the log file that is enough to reproduce the issue:

[server.log](https://github.com/otros-systems/otroslogviewer/files/8812979/server.log)

Otros only shows the first entry of the log file, the other two entries are not shown. Some parts of the entry are not parsed correctly like e.g. the milliseconds of the timestamp in this case:

![otros](https://user-images.githubusercontent.com/38068125/171376103-e8938bfb-0241-47dc-b613-708ec78bc1cc.png)

If you remove the last line or more of the stacktrace OR if there is another shorter entry before this long stacktrace, opening the file works without a problem.

**Comment by svennissel** [comment]
I think you use the wrong log parser. Create a file under <USER-HOME>/.otroslogviewer/plugins/logimporters/server.patter with following content:

```
type=log4j
pattern=TIMESTAMP LEVEL [LOGGER] (THREAD) MESSAGE
dateFormat=yyyy-MM-dd HH:mm:ss,SSS
name=server
charset=utf8
```
Now if you open the file you can choose the parser "server". 

![grafik](https://user-images.githubusercontent.com/40182921/173929732-8bda667a-b7fe-443c-bf15-3aef3d7bf227.png)

**Comment by svennissel** [comment]
See also [Wiki Log4jPatternLayout](https://github.com/otros-systems/otroslogviewer/wiki/Log4jPatternLayout
)

**Comment by jthalmai** [comment]
Thanks for your reply. I see that the pattern/parser is my problem. 
In fact I do have a working pattern, but I usually do not access my logs via the menu entry 'File > open log files' but just drag the log files from Windows explorer directly to Otros.
In a quite old version from Otros this worked but current versions seem to use the 'JUL simple formatter' when opening log files with drag and drop. No popup to select a parser comes up like when you open it from the menu. Is there a way to use my pattern as the default parser instead of the JUL formatter?
