### ISSUE TITLE
Is it possible to use otroslogviewer with a GUI platform other than Swing?

### ISSUE THREAD

**Issue by PavelTurk** [otros-systems/otroslogviewer#645]
Using search I've found out that swing is used not only in GUI module but also in other modules, for example in core. Can anyone say, if it possible to use otroslogviewer with a GUI platform other than Swing, for example, with JavaFX, web etc.  

I mean does its architecture support using it with different GUI platforms?

**Comment by svennissel** [comment]
Sorry. We don't Support a other UI. We have a Plugin system for the Filters.

**Comment by PavelTurk** [comment]
@svennissel Thank you for your answer. You mentioned Filters. Do I understand it correctly that all main logic is in Filters, so, it is possible to use them for logviewers built for another GUI platforms? By other words, I need all logic without swing.

**Comment by svennissel** [comment]
It is a little Bit modular. I think you can use a lot of in other Projects, but Not all. But this ist a good idear.
